### ISSUE TITLE
Needs Node.js to build the WAR

### ISSUE THREAD

**Issue by KewlCat** [sismics/reader#111]
Hi

I'm trying to build release 1.4 from source, following the instructions found in the README. When in reader-web, if I run "mvn -Pprod -DskipTests clean install" it fails when trying to execute "npm". It further fails while trying to run "grunt".
Does this mean that I must have Node.js installed in order to build the war ?

**Comment by jendib** [comment]
That's true, it's needed to concat the JS files, minify them, and some other stuff.

**Comment by KewlCat** [comment]
Isn't that akin to using a flamethrower to kill a mosquito ?
In order to minify JS (and CSS) files, yuicompressor is directly usable in ant tasks :
https://github.com/sbuckle/yui-compressor-ant-task/
(it's what we use at work ; never had a bad surprise with it)

**Comment by jendib** [comment]
Grunt is also used to compile LESS into CSS, replace some HTML blocks and variables.
It seems very well suited for linear front-end building tasks (and it's what Grunt is built for).

**Comment by naku** [comment]
Use the NPM maven plugin to remove node / NPM from the external dependencies
