### ISSUE TITLE
Themes absent from the release WAR

### ISSUE THREAD

**Issue by KewlCat** [sismics/reader#112]
Hi

I've tried to make a clean install of the 1.4 release of Sismics reader, and while everything seems to work OK, there is nothing appearing in the "Theme" dropdown list. It looks like the "theme" subdirectory is simply not there.
![sismics-theme](https://cloud.githubusercontent.com/assets/4947201/7592366/32de88c2-f8d3-11e4-9d55-99e8bbd8fa71.png)

**Comment by jendib** [comment]
That's indeed right, themes have been fixed in a commit later to 1.4 release (https://github.com/sismics/reader/commit/d2c86ca00096b1512a14c3f4402f89890d1265d7).
Sorry for that!
