### ISSUE TITLE
"article.subscription" instead of feed name (?)

### ISSUE THREAD

**Issue by KewlCat** [sismics/reader#113]
Hi

When browsing by "Latest - Unread" the feed name and author name (?) do not show up, and are instead replaced with "article.subscription" and  "article.creator".
![sismics label](https://cloud.githubusercontent.com/assets/4947201/7593549/462f7e60-f8db-11e4-8bd0-240af6ada953.png)

**Comment by jendib** [comment]
On https://reader-demo.sismics.com (which is ~= master branch), it seems to work fine.
Did you try cleaning your browser cache?

**Comment by KewlCat** [comment]
Well, I tried to "Shift-Reload", "Ctrl-Shift-R", etc. etc. to no avail. After removing cache files, the author name and feed name are finally here.

Thank you
