### ISSUE TITLE
Dependency for Android N

### ISSUE THREAD

**Issue by manparvesh** [sismics/reader#130]
The Android application can be upgraded for newer Android versions like 6 and 7.

**Comment by jendib** [comment]
What do you mean? The Android app should already works on Android N, regardless of the target SDK.

**Comment by manparvesh** [comment]
I meant that there must be many new features that must've been added in 6 and 7 that can be used instead of the older ones.

**Comment by jendib** [comment]
Can you be more specific? The new features in Android 6 don't replace the old ones. They are just new.
Moreover, the Reader Android app targets API 14 (Android 4) for maximum compatibility.

**Comment by manparvesh** [comment]
Guess I was overthinking about the dependencies for latest platforms. Closing the issue.

**Comment by jendib** [comment]
No problem, feedbacks are always welcome ;)
