### ISSUE TITLE
UI improvements in website

### ISSUE THREAD

**Issue by manparvesh** [sismics/reader#131]
I feel like the website's UI can be improved a lot. 

- One thing that bothers me is the group of social media sharing buttons displayed below an image in a post, in addition to the ones below each post. This can be replaced by some buttons that are initially hidden and when a user hovers over the picture, they are displayed. The location of these buttons would be on the right or left corner of the photo.
- The left panel for subscriptions can be hidden or at least an option should be provided to hide it. Or we can use a slide-out navigation menu for this. (Something like [this](https://mango.github.io/slideout/))
- The picture buttons on top should show some hints for what they are there for. They are confusing.
- Have you considered using Material design for the website?

**Comment by jendib** [comment]
- There is no social media buttons on images, only on the bottom of each post. Maybe you have a browser extension which adds them?
- The left panel can't be hidden on a big screen (computer) you're right, but it can be hidden when the screen gets smaller (tablet or phone). Maybe it's what you seek?
- The top buttons are confusing, I agree. We should add a tooltip to explain what they do. PR are welcome ;)
- I'm not a fan of material design for web UI :)

**Comment by manparvesh** [comment]
- ![image](https://cloud.githubusercontent.com/assets/6629115/14768246/4255766e-0a5a-11e6-92fa-a9258fa9df1a.png)
I use chrome but, just to check if there is some extension messing with my connection, I ran the website on Microsoft Edge which does not contain any extensions. Still seeing these buttons. Today I clicked on one and saw that these were for sharing of the post and not for an image.  
- Personally, I think that the users should be given an option for hiding the left panel because for me that part would be distracting when reading a post.
- I'm not experienced with website development, but I surely wish to try it out sometime in the future. I'll try to incorporate some changes that I mentioned and submit a PR whenever I get time.
- That's fine. I just wanted to know if you had thought of it :)
- Another thing I noticed some time ago. I saw a screenshot of the mobile website [here](https://www.sismics.com/reader/img/screenshots/big/4-big.png). In my opinion, the text should be properly indented (like the time, and the text after the image should start from a new line).

**Comment by jendib** [comment]
- Those buttons are added by Mashable, not Reader (you can see there is no buttons on the other feeds). Unfortunately we can't do much for those :/
- If you want to submit a PR to have the foldable panel even on large screen, we'll merge it, no problem ;)
- The screenshot of the mobile website is outdated, we should update it. It's better on the current app.

I made a new issue for the tooltips [here](https://github.com/sismics/reader/issues/133)

**Comment by manparvesh** [comment]
Great! I'll let you know whenever I'll be free (I have my exams in a few days so won't be able to devote much time) if that issue is not resolved already :)
