### ISSUE TITLE
No documentation about HTTPS support

### ISSUE THREAD

**Issue by jlm451** [sismics/reader#141]
I noticed this [issue 20](https://github.com/sismics/reader/issues/20), but reader --help, the [help page](https://www.sismics.com/reader/#!/help), and searching don't return any information about HTTPS support. Does the documentation exist? If not, perhaps I could write it given information.

**Comment by Thomas-Gt** [comment]
+1

**Comment by jendib** [comment]
- Standalone version : The reader.sh file must be edited (https://github.com/sismics/reader/blob/master/reader-distribution-standalone/src/main/assembly/reader.sh) to configure SSL
- Windows version : There is a settings panel in the UI to configure SSL
