### ISSUE TITLE
Error importing from OPML

### ISSUE THREAD

**Issue by JauntyTGD** [sismics/reader#154]
Import Progress stops with no error, and no way to cancel/abort. 
Persists after restarting Sismics, or logging out and back in.  
This prevents me from being able to dismiss completed import progress bars

![image](https://user-images.githubusercontent.com/31256226/29584929-4eea1f48-8753-11e7-8061-0a39eec5a0ff.png)

**Comment by jendib** [comment]
Can you please join your full reader logs?

**Comment by JauntyTGD** [comment]
Here you are
[reader-log.txt](https://github.com/sismics/reader/files/1243245/reader-log.txt)

**Comment by jendib** [comment]
It's the database logs. Do you have a reader.log file? It shouldn't be far.

**Comment by JauntyTGD** [comment]
Sorry, as far as I could tell that was it: I simply made a copy and renamed it from reader.log to reader-log.txt so as to be able to attach it to the post (since git didn't allow the filetype)

I retrieved it from [...]\AppData\Roaming\Sismics\Reader\db\reader.log
I've made another copy here since then
[reader log.txt](https://github.com/sismics/reader/files/1243355/reader.log.txt)

**Comment by jendib** [comment]
You have nothing here: \AppData\Roaming\Sismics\Reader\log ?

**Comment by JauntyTGD** [comment]
Oh no, I do of course. Sorry for making such an obvious mistake
[reader.log.txt](https://github.com/sismics/reader/files/1243369/reader.log.txt)

**Comment by jendib** [comment]
How many times did you try to import your OPML file?

**Comment by JauntyTGD** [comment]
I believe I attempted the failed file twice, but I'm not certain.

**Comment by jendib** [comment]
It looks like the error is:
```
Error processing import file \AppData\Local\Temp\reader_opml_import8058655338571952660.tmp 
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
```
Can you provide the failing OPML file?

**Comment by jendib** [comment]
I just imported successfully your file here (available for 4h, login with admin/admin): http://pwd10-0-48-3-8123.host1.labs.play-with-docker.com

**Comment by JauntyTGD** [comment]
thanks for your help, I appreciate it
