### ISSUE TITLE
"Error retrieving feed" for properly formatted feed. 

### ISSUE THREAD

**Issue by JauntyTGD** [sismics/reader#155]
I consistently receive the error

> Error retrieving feed at 

when attempting to add the feed from https://tim.blog/feed/ using sismics. 
verified the feed can be added to diggreader & rssowl

**Comment by jendib** [comment]
I manage to add this feed on my local Reader instance without any issue. Can you share your log file if you need any more assistance?
![image](https://user-images.githubusercontent.com/2623413/30885010-fd658998-a311-11e7-9a3a-ff5a6673f632.png)

**Comment by JauntyTGD** [comment]
Sure
[reader.log.txt](https://github.com/sismics/reader/files/1335374/reader.log.txt)

**Comment by jendib** [comment]
You seem to have an old version of Java, which does not contain the root certificate of tim.blog. Update your JVM to version 8u101 to fix the issue.

**Comment by JauntyTGD** [comment]
Thank you, will do
