### ISSUE TITLE
Open Reader support

### ISSUE THREAD

**Issue by valdotdev** [sismics/reader#158]
Will Sismics reader eventually support the [Open Reader API](https://rss-sync.github.io/Open-Reader-API/rssconsensus/)? I got a lot of feeds in services like [Inoreader](http://www.inoreader.com/) So rather than just exporting/importing a JSON/OPML file, Sismics could just sync with external services. Sorry in advance if this was already talked about.

Thanks.

**Comment by jendib** [comment]
That's a good idea, however this API is not finished: http://rss-sync.github.io/Open-Reader-API/stream/

**Comment by valdotdev** [comment]
@jendib Oh ok. I just thought it's already plausible since apps like Vienna or Reeder supports services like Inoreader which they claim uses Open Reader.

**Comment by jendib** [comment]
Indeed it looks like these clients are using the proprietary API of a few services.
This issue https://github.com/sismics/reader/issues/157 suggesting to implement the Fever API could be a better idea to support those clients.
