### ISSUE TITLE
API calls

### ISSUE THREAD

**Issue by joogoo** [sismics/reader#159]
It's not really an issue but rather a question about reader's capabilities.

I would like to proceed to a natural language analysis on retrieved articles in order to categorize publications. 

Do you think it's possible to make direct calls on reader API  ? And if so, can you detail the way to do that ?

Thanks a lot !

**Comment by jendib** [comment]
Yes of course, first you need to login:
POST /api/user/login with "username" and "password" parameters
It will give you an authentication cookie with a Set-Cookie header. Save it and provide it in the following API calls (in a Cookie header).

Then to fetch all articles, you can call:
GET /api/all?unread=false&limit=50 for the first page
GET /api/all?unread=false&limit=50&after_article=<id of the last article> for the following pages

Don't hesitate to inspect the network traffic in your browser while you are using Reader to check other API endpoints.

**Comment by joogoo** [comment]
Fantastic !

This works as expected.
I'll have look the network traffic to get hints on the other API endpoints.
