### ISSUE TITLE
After installation = Launcher error - System cannot find set path

### ISSUE THREAD

**Issue by 9837867dfdb138f20** [sismics/reader#163]
OS: Windows 7 Ultimate 64-bit

I installed from site windows installer and this shows after installation and when trying to run application through reader-agent.exe, reader-agent.jar, reader-agent-elevated.exe. Re-install doesn't help.

**Comment by jendib** [comment]
Do you have any log in `C:\Users\<You>\AppData\Roaming\Sismics\Reader` ?

**Comment by 9837867dfdb138f20** [comment]
yup

https://i.imgur.com/Ao0z7LE.jpg
