### ISSUE TITLE
Update iFrame Whitelist

### ISSUE THREAD

**Issue by naku** [sismics/reader#99]
Sample URL https://movies.yahoo.com/video/internets-own-boy-story-aaron-161415661.html?format=embed&amp;player_autoplay=false

**Comment by naku** [comment]
//embed.spotify.com/?uri=spotify:album:3NNSJt3gWSmPmnjCwZyLA5

**Comment by naku** [comment]
//soundsgood.co/embed/5634c158722be1b60e7651be

**Comment by jendib** [comment]
http://cdn.livestream.com/embed/spaceflightnow?layout=4&height=340&width=560&autoplay=false
http://v.24liveblog.com/live/?id=1312491

**Comment by naku** [comment]
//fiddle.jshell.net/toddmotto/0oarywLe/show/light/ (from https://toddmotto.com/stateless-angular-components)

**Comment by naku** [comment]
//embed-ssl.ted.com/talks/tim_urban_inside_the_mind_of_a_master_procrastinator.html (from http://waitbutwhy.com/2016/03/my-ted-talk.html)

**Comment by naku** [comment]
//twitch.tv/gl_geekinc (from http://korben.info/keynote-apple-rendez-aujourdhui-a-17h45.html)

**Comment by naku** [comment]
//www.facebook.com/plugins/video.php (from https://coconuts.co/bangkok/news/feasting-fatty-obese-macaque-released-fat-camp-hours-ago-seen-gorging-video/)
